### ISSUE TITLE
Support custom groups for custom nodes

### ISSUE THREAD

**Issue by chimaeraUndying** [zGraund/CreateReAutomated#6]
(or am I just implementing custom nodes wrong?)

Hi, me again. Working with 0.3.2 and a KubeJS + datapack setup to implement some custom nodes. I've got them generating fine and everything, but I'm finding that I have to hijack the existing groups to do so.

eg. for an emerald node I'm doing...

in `configured_feature/emerald_node.json`:
```json
{
  "type": "createreautomated:encased_node",
  "config": {
    "group": "copper",
     <etc.>
}
```

in `placed_feature/emerald_node_placed.json`:
```json
{
  "feature": "kubejs:emerald_node",
  "placement": [
    {
      "type": "createreautomated:config_filter"
    },
    {
      "type": "createreautomated:config_node_placement",
      "group": "copper"
    },
    {
      "type": "minecraft:in_square"
    }
  ]
}
```

... as there's no way to use "emerald" for the group; anything entered there other than what's used for nodes in the mod causes an error like
```yaml
[com.structureessentials.StructureEssentials/]: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/configured_feature]: kubejs:emerald_node
```

**Comment by zGraund** [comment]
The "group" field in the config of the `encased_node` feature in `configured_feature/emerald_node.json` (which controls the number of faces that a node must have touching an ore to spawn) refers to the groups in the [mod config](https://github.com/zGraund/CreateReAutomated/blob/3e231206cec1d2c323ccec063bac242873ee0eb9/src/main/java/com/github/zgraund/createreautomated/config/Worldgen.java#L32). These are the groups you can change in the config file or in game. If you don't want to, or can't, use an existing group, you can specify a hardcoded value by using "faces" instead of "group":

```json
{
  "type": "createreautomated:encased_node",
  "config": {
    "faces": 3,
    "targets": [ ]
  }
}
```

The same goes for `placed_feature/emerald_node_placed.json`. By using `"type": "createreautomated:config_node_placement"`, you are using the values from the config. The good news is that, in the placed feature, you can use any vanilla worldgen settings. For example:

```json
{
  "feature": "kubejs:emerald_node",
  "placement": [
    {
      "type": "createreautomated:config_filter"
    },
    {
      "type": "minecraft:count",
      "count": 20
    },
    {
      "type": "minecraft:height_range",
      "height": {
        "type": "minecraft:uniform",
        "max_inclusive": {
          "absolute": 128
        },
        "min_inclusive": {
          "absolute": 64
        }
      }
    },
    {
      "type": "minecraft:in_square"
    }
  ]
}
```

This will pick 20 positions between 64 and 128 and then spread them throughout the chunk. The count and height are combined into the same config when using `createreautomated:config_node_placement`, so you will need to specify both to get the same result. You can do whatever you like with the vanilla configs in there. The only thing you should keep is the `"type": "createreautomated:config_filter"` at the top, because that will prevent the node from spawning if the mod worldgen is disabled.

In hindsight, the name `group` was probably not clear enough, but I don't think I'm going to change it because I don't want to break all existing datapacks.

**Comment by chimaeraUndying** [comment]
Makes total sense, thanks! This is what I get for ripping stuff straight out of data/
